name: Build + Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Развертывать при пуше в ветку main (или master, если вы используете ее)
  # Добавьте workflow_dispatch для возможности запуска вручную из интерфейса GitHub
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu
    # Необходимые разрешения для записи в репозиторий (для peaceiris/actions-gh-pages)
    permissions:
      contents: write
      pages: write # Добавьте, если используете новый способ деплоя через GitHub Pages Action
      id-token: write # Добавьте, если используете новый способ деплоя через GitHub Pages Action

    steps:
      - name: Checkout 🏗️
        uses: actions/checkout@v4 # Используем последнюю стабильную версию

      - name: Enable Corepack
        run: corepack enable # Включаем Corepack для управления версиями пакетных менеджеров

      - name: Setup Node.js 🛠️
        uses: actions/setup-node@v4 # Используем последнюю стабильную версию
        with:
          node-version: 20 # Указываем конкретную LTS версию Node.js
          cache: 'yarn' # Настраиваем кеширование для Yarn
          corepack: true # Указываем использовать Corepack

      - name: Install dependencies 📦
        # Так как вы используете Yarn PnP, достаточно просто запустить 'yarn'.
        # '--immutable' рекомендуется для CI, чтобы гарантировать воспроизводимость.
        run: yarn install --immutable

      - name: Build website 🔨
        # Запускаем ваш production Webpack скрипт, который теперь учитывает publicPath
        run: yarn build

      - name: Setup Pages # Шаг настройки окружения Pages (требуется для нового способа деплоя)
        uses: actions/configure-pages@v5 # Используем последнюю стабильную версию

      - name: Upload artifact for Pages # Загрузка артефакта для деплоя
        uses: actions/upload-pages-artifact@v3 # Используем последнюю стабильную версию
        with:
          # Указываем путь к папке со собранными файлами,
          # которая будет загружена как артефакт
          path: './dist'

      - name: Deploy to GitHub Pages 🚀 # Шаг деплоя
        id: deployment # Присваиваем ID для возможности ссылаться на этот шаг
        uses: actions/deploy-pages@v4 # Используем последнюю стабильную версию
        # У этого action нет входных параметров publish_dir или publish_branch,
        # он использует артефакт, загруженный предыдущим шагом actions/upload-pages-artifact