name: Build + Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Развертывать при пуше в ветку main
  workflow_dispatch: # Возможность запуска вручную

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Для checkout
      pages: write # Для actions/deploy-pages
      id-token: write # Для actions/deploy-pages

    steps:
      - name: Checkout 🏗️
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js 🛠️
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Используйте конкретную LTS версию
          cache: 'yarn'
          corepack: true

      - name: Install dependencies 📦
        run: yarn install --immutable # Устанавливаем зависимости

      - name: Build website 🔨
        # Запускает ваш скрипт 'build' из package.json, который использует Webpack
        run: yarn build

      # Следующие 3 шага используют новый, рекомендуемый способ деплоя на GitHub Pages

      - name: Setup Pages # Настройка окружения Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages # Загрузка собранных файлов как артефакта Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Путь к папке со собранными файлами, указанной в webpack.config.js output.path
          path: './dist'

      - name: Deploy to GitHub Pages 🚀 # Деплой артефакта на Pages
        id: deployment
        uses: actions/deploy-pages@v4