name: Build + Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Запускаем workflow при пуше в ветку main
  workflow_dispatch: # Возможность запуска вручную

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      # Для peaceiris/actions-gh-pages достаточно разрешения на запись содержимого
      contents: write
    steps:
      - name: Checkout 🏗️
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js 🛠️
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Используйте конкретную LTS версию
          cache: 'yarn'

      - name: Install dependencies 📦
        run: yarn install --immutable

      - name: Build website 🔨
        run: yarn build # Этот шаг собирает проект в папку ./dist

      # Опционально: Создаем файл .nojekyll для предотвращения обработки Jekyll
      # Добавьте этот шаг, если у вас возникают проблемы с пропуском файлов/папок,
      # начинающихся с подчеркивания (_)
      # - name: Create .nojekyll file
      #   run: touch ./dist/.nojekyll


      # !!! ВОЗВРАЩЕНО: Деплой в ветку gh-pages с использованием peaceiris/actions-gh-pages !!!
      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v4 # Используем экшен для деплоя в ветку gh-pages
        with:
          # GitHub автоматически предоставляет токен с необходимыми разрешениями
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Папка с готовым сайтом, которую нужно опубликовать
          publish_dir: ./dist
          # Ветка, в которую будет опубликован сайт для GitHub Pages
          publish_branch: gh-pages
          # Опционально: Настроить автора коммита в ветке gh-pages
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'